### ISSUE TITLE
How to uninstall changes?

### ISSUE THREAD

**Issue by TomErnst1972** [extremeshok/xshok-proxmox#71]
Installed your script, but it brakes my network traffic from LCX containers and made my home internal DNS resolving impossible (runing pihole as LX on the host)

So, how can i reverse the changes made? there is a closed issue with the same question, but no documentation...

best regards,
Tom

**Comment by TomErnst1972** [comment]
there are errors in the journal, i did not had before:
Couldn't write '0' to 'net/ipv4/tcp_tw_recycle', ignoring: No such file or directory
Jul 07 14:37:27 pve-xps systemd-sysctl[957]: Couldn't write '60' to 'net/netfilter/nf_conntrack_generic_timeout', ignoring: No such file or directory
Jul 07 14:37:27 pve-xps systemd-sysctl[957]: Couldn't write '0' to 'net/netfilter/nf_conntrack_helper', ignoring: No such file or directory
Jul 07 14:37:27 pve-xps systemd-sysctl[957]: Couldn't write '524288' to 'net/netfilter/nf_conntrack_max', ignoring: No such file or directory
Jul 07 14:37:27 pve-xps systemd-sysctl[957]: Couldn't write '28800' to 'net/netfilter/nf_conntrack_tcp_timeout_established', ignoring: No such file or dire>
Jul 07 14:37:27 pve-xps kernel: thermal thermal_zone4: failed to read out thermal zone (-61)

**Comment by TomErnst1972** [comment]
found out myself. they were in /etc/sysctl.d/*.conf
all is back to normal... *sigh

**Comment by jtabox** [comment]
Honestly, this project hasn't been touched since May last year. The versions of Debian and Proxmox it was developed and tested on are not their current ones. This last year both Debian and Proxmox have had a major version update (Proxmox went from 7 to 8 and its Debian went from 11 to 12).
This script makes a lot of changes in system files and configurations when it runs, so it has very high risk to break something. You should either read the script and adjust/deactivate stuff on your own, or search github for forks of this project that have been updated more recently than 15 months ago. It will spare a lot of headaches :)

**Comment by TomErnst1972** [comment]
> You should either read the script and adjust/deactivate stuff on your own, or search github for forks of this project that have been updated more recently than 15 months ago. It will spare a lot of headaches :)

exactly did that, thou i was a bit lazy in the beginning to do so... :-) thx anyway, as parts of your script are very useful!
